name: pve
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pymc>=5
  - arviz
  - pandas
  - numpy
  - scipy
  - openpyxl
  - xlsxwriter
  - jupyter
  - jupyterlab
  - pyarrow
  - pip
  - pip:
      - cfbd
      - python-dotenv
      - PuLP
